package Sites;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Class        SiteDetails.java
 * Description  A class representing the SiteDetails JDialog
 * Date         10/06/2023     
 * @author      <i>Kirill Grichanichenko</i>           
 *****************************************************************************/
public class SiteDetails extends javax.swing.JDialog {

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    * Constructor  SiteDetials() - Constructor
    * Description  A class representing the siteDetails JDialog
    * Date         10/06/2023     
    * @author      <i>Kirill Grichanichenko</i>           
    * @param       parent     java.awt.Frame           
    * @param       modal      Boolean           
    * @param       name       String          
    * @param       country    String       
    * @param       population float    
    * @param       capital    String
    * @param       area       float
    *****************************************************************************/
    public SiteDetails(java.awt.Frame parent, boolean modal, String name, String country, float population, String capital, float area) {
        
    super(parent, modal);
    initComponents();
    
    this.getRootPane().setDefaultButton(closeJButton);
    this.setLocationRelativeTo(null);
    setAlwaysOnTop(true);
    setModal(true);
    
    titleJLabel.setText(name);
    
    // Adds pictures to the LogoJLabel
    try {
        logoJLabel.setIcon(new javax.swing.ImageIcon("src/Images/" + country + "Flag.png"));
    } catch (java.lang.NullPointerException evt) {
        logoJLabel.setIcon(null);
    }
    
    try {
        String filePath = "src/Data/" + country + ".txt";
        File file = new File(filePath);
    
        Scanner scanner = new Scanner(file);
        StringBuilder content = new StringBuilder();
    
        while (scanner.hasNextLine()) {
            content.append(scanner.nextLine()).append("\n");
        }
    
        scanner.close();;
    
        infoJTextArea.setText(content.toString());
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    }

    // Set the text information about the site.
    infoJTextArea.append("\nName: " + name + "\nCountry: " + country + "\nPopulation: "
            + population + " million" +"\nCapital: " + capital + "\nArea: " + area + " sq. miles");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        logoJLabel = new javax.swing.JLabel();
        infoJScrollPane = new javax.swing.JScrollPane();
        infoJTextArea = new javax.swing.JTextArea();
        closeJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleJLabel.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(0, 102, 255));
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Title");

        infoJTextArea.setEditable(false);
        infoJTextArea.setColumns(20);
        infoJTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infoJTextArea.setLineWrap(true);
        infoJTextArea.setRows(5);
        infoJTextArea.setWrapStyleWord(true);
        infoJScrollPane.setViewportView(infoJTextArea);

        closeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeJButton.setMnemonic('C');
        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(infoJScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    * Method       cancelJButtonActionPerformed()
    * Description  An event handler that exits the JDialog
    * Date         10/06/2023     
    * @author      <i>Kirill Grichanichenko</i>
    * @param       evt java.awt.event.ActionEvent
    *****************************************************************************/
    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JScrollPane infoJScrollPane;
    private javax.swing.JTextArea infoJTextArea;
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
